version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - go version
  pre_build:
    commands:
      # Install Go module dependencies
      - echo "Fetching Go modules"
      - go mod tidy
  build:
    commands:
      - echo "Building the Go application..."
      - GOOS=linux GOARCH=amd64 go build -o server main.go
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - server
