version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - go version
      - wget https://dl.google.com/go/go1.22.5.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version
  pre_build:
    commands:
      # Install Go module dependencies
      - echo "Fetching Go modules"
      - go mod tidy
  build:
    commands:
      - echo "Building the Go application..."
      - GOOS=linux GOARCH=amd64 go build -o server main.go
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - server
    - appspec.yml
    - scripts/**
