version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt install golang-go
  build:
    commands:
      - echo "Building the Go application..."
      - GOOS=linux GOARCH=amd64 go build -o server main.go
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - server
